<?php

/**
 * @file
 * Contains Drupal\content_entity_example\content_entity_example.module
 */

/**
 * @defgroup content_entity_example Example: Content Entity
 * @ingroup examples
 * @{
 * Example of how to define a content entity.
 * }
 */

/**
 * Implements hook_permission().
 */
function content_entity_example_permission() {
  return array(
    'delete content_entity_example entity' => array(
      'title' => t('Delete entity content.'),
    ),
    'add content_entity_example entity' => array(
      'title' => t('Add entity content'),
    ),
    'view content_entity_example entity' => array(
      'title' => t('View entity content'),
    ),
    'edit content_entity_example entity' => array(
      'title' => t('Edit entity content'),
    ),
    'admininister content_entity_example entity' => array(
      'title' => t('Administer settings'),
    ),
  );
}
